/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import domain.Person;
import javax.swing.JOptionPane;

/**
 *
 * @author student1
 */
public class FrmPersonv4 extends javax.swing.JFrame {

    /**
     * Creates new form FrmPersonv4
     */
    public FrmPersonv4() {
        initComponents();
         prepareMenu();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        inputPerson = new components.fields.PanelInputPersonv2();
        btnSubmit = new javax.swing.JButton();
        jMenuBar = new javax.swing.JMenuBar();
        jMenuConfiguration = new javax.swing.JMenu();
        jRadioButtonMenuItemForm1 = new javax.swing.JRadioButtonMenuItem();
        jRadioButtonMenuItemForm2 = new javax.swing.JRadioButtonMenuItem();
        jRadioButtonMenuItemForm3 = new javax.swing.JRadioButtonMenuItem();
        jRadioButtonMenuItemForm4 = new javax.swing.JRadioButtonMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnSubmit.setText("Submit");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });

        jMenuConfiguration.setText("Configure input");

        jRadioButtonMenuItemForm1.setSelected(true);
        jRadioButtonMenuItemForm1.setText("Form1");
        jRadioButtonMenuItemForm1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonMenuItemForm1ActionPerformed(evt);
            }
        });
        jMenuConfiguration.add(jRadioButtonMenuItemForm1);

        jRadioButtonMenuItemForm2.setSelected(true);
        jRadioButtonMenuItemForm2.setText("Form2");
        jRadioButtonMenuItemForm2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonMenuItemForm2ActionPerformed(evt);
            }
        });
        jMenuConfiguration.add(jRadioButtonMenuItemForm2);

        jRadioButtonMenuItemForm3.setSelected(true);
        jRadioButtonMenuItemForm3.setText("Form3");
        jRadioButtonMenuItemForm3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonMenuItemForm3ActionPerformed(evt);
            }
        });
        jMenuConfiguration.add(jRadioButtonMenuItemForm3);

        jRadioButtonMenuItemForm4.setSelected(true);
        jRadioButtonMenuItemForm4.setText("Form4");
        jRadioButtonMenuItemForm4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonMenuItemForm4ActionPerformed(evt);
            }
        });
        jMenuConfiguration.add(jRadioButtonMenuItemForm4);

        jMenuBar.add(jMenuConfiguration);

        setJMenuBar(jMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(inputPerson, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnSubmit)
                        .addGap(18, 18, 18))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(inputPerson, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSubmit)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        // TODO add your handling code here:
        Person person = (Person) inputPerson.getValue();
        JOptionPane.showMessageDialog(this, person.toString(), "Person is saved.", JOptionPane.INFORMATION_MESSAGE);

    }//GEN-LAST:event_btnSubmitActionPerformed

    private void jRadioButtonMenuItemForm1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonMenuItemForm1ActionPerformed
        new FrmPerson().setVisible(true);
        dispose();
    }//GEN-LAST:event_jRadioButtonMenuItemForm1ActionPerformed

    private void jRadioButtonMenuItemForm2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonMenuItemForm2ActionPerformed
        new FrmPersonv2().setVisible(true);
        dispose();
    }//GEN-LAST:event_jRadioButtonMenuItemForm2ActionPerformed

    private void jRadioButtonMenuItemForm3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonMenuItemForm3ActionPerformed
        new formPersonv3().setVisible(true);
        dispose();
    }//GEN-LAST:event_jRadioButtonMenuItemForm3ActionPerformed

    private void jRadioButtonMenuItemForm4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonMenuItemForm4ActionPerformed
         jRadioButtonMenuItemForm3.setSelected(true);
    }//GEN-LAST:event_jRadioButtonMenuItemForm4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmPersonv4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmPersonv4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmPersonv4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmPersonv4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmPersonv4().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSubmit;
    private components.fields.PanelInputPersonv2 inputPerson;
    private javax.swing.JMenuBar jMenuBar;
    private javax.swing.JMenu jMenuConfiguration;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItemForm1;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItemForm2;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItemForm3;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItemForm4;
    // End of variables declaration//GEN-END:variables

    private void prepareMenu() {
          jRadioButtonMenuItemForm1.setSelected(false);
         jRadioButtonMenuItemForm2.setSelected(false);
         jRadioButtonMenuItemForm3.setSelected(false);
         jRadioButtonMenuItemForm4.setSelected(true);
    }
}
