/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import domain.Gender;
import domain.Person;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author student1
 */
public class FrmPersonv2 extends javax.swing.JFrame {

    /**
     * Creates new form FrmPersonv2
     */
    public FrmPersonv2() {
        initComponents();
         prepareMenu();
        prepareView();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        inputFirstName = new components.fields.PanelInputTextField();
        inputLastName = new components.fields.PanelInputTextField();
        btnSubmit = new javax.swing.JButton();
        inputGender = new components.fields.PanelInputRadio();
        inputDate = new components.fields.PanelInputDatePicker();
        jMenuBar = new javax.swing.JMenuBar();
        jMenuConfiguration = new javax.swing.JMenu();
        jRadioButtonMenuItemForm1 = new javax.swing.JRadioButtonMenuItem();
        jRadioButtonMenuItemForm2 = new javax.swing.JRadioButtonMenuItem();
        jRadioButtonMenuItemForm3 = new javax.swing.JRadioButtonMenuItem();
        jRadioButtonMenuItemForm4 = new javax.swing.JRadioButtonMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnSubmit.setText("Submit");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });

        jMenuConfiguration.setText("Configure input");

        jRadioButtonMenuItemForm1.setSelected(true);
        jRadioButtonMenuItemForm1.setText("Form1");
        jRadioButtonMenuItemForm1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonMenuItemForm1ActionPerformed(evt);
            }
        });
        jMenuConfiguration.add(jRadioButtonMenuItemForm1);

        jRadioButtonMenuItemForm2.setSelected(true);
        jRadioButtonMenuItemForm2.setText("Form2");
        jRadioButtonMenuItemForm2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonMenuItemForm2ActionPerformed(evt);
            }
        });
        jMenuConfiguration.add(jRadioButtonMenuItemForm2);

        jRadioButtonMenuItemForm3.setSelected(true);
        jRadioButtonMenuItemForm3.setText("Form3");
        jRadioButtonMenuItemForm3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonMenuItemForm3ActionPerformed(evt);
            }
        });
        jMenuConfiguration.add(jRadioButtonMenuItemForm3);

        jRadioButtonMenuItemForm4.setSelected(true);
        jRadioButtonMenuItemForm4.setText("Form4");
        jRadioButtonMenuItemForm4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonMenuItemForm4ActionPerformed(evt);
            }
        });
        jMenuConfiguration.add(jRadioButtonMenuItemForm4);

        jMenuBar.add(jMenuConfiguration);

        setJMenuBar(jMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(inputFirstName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(inputLastName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(inputDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(42, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(inputGender, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(81, 81, 81))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSubmit)
                .addGap(53, 53, 53))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(inputFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inputLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(inputDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inputGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSubmit)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        // TODO add your handling code here:
         Person person = new Person();
        person.setFirstName((String) inputFirstName.getValue());
        person.setLastName((String) inputLastName.getValue());
        try {
         person.setDate(new SimpleDateFormat("dd.MM.yyyy").parse(inputDate.getValue().toString()));
        } catch (Exception ex) {
            Logger.getLogger(FrmPerson.class.getName()).log(Level.SEVERE, null, ex);
            inputDate.getLblError().setText(ex.getMessage());
            return;
        }
        try {
            person.setGender(Gender.valueOf((String) inputGender.getValue()));
        } catch (Exception e) {
            inputGender.getLblError().setText(e.getMessage());
        }
        JOptionPane.showMessageDialog(this, person.toString(),"Person is saved.", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnSubmitActionPerformed

    private void jRadioButtonMenuItemForm1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonMenuItemForm1ActionPerformed
        new FrmPerson().setVisible(true);
        dispose();
    }//GEN-LAST:event_jRadioButtonMenuItemForm1ActionPerformed

    private void jRadioButtonMenuItemForm2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonMenuItemForm2ActionPerformed
        jRadioButtonMenuItemForm2.setSelected(true);
    }//GEN-LAST:event_jRadioButtonMenuItemForm2ActionPerformed

    private void jRadioButtonMenuItemForm3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonMenuItemForm3ActionPerformed
        new formPersonv3().setVisible(true);
        dispose();
    }//GEN-LAST:event_jRadioButtonMenuItemForm3ActionPerformed

    private void jRadioButtonMenuItemForm4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonMenuItemForm4ActionPerformed
        new FrmPersonv4().setVisible(true);
        dispose();
    }//GEN-LAST:event_jRadioButtonMenuItemForm4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmPersonv2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmPersonv2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmPersonv2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmPersonv2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmPersonv2().setVisible(true);
            }
        });
    }
       private void prepareView() {
        inputFirstName.getLblFieldText().setText("First name:");
        inputFirstName.getLblError().setText("");
        inputLastName.getLblFieldText().setText("Last name:");
        inputLastName.getLblError().setText("");
        inputDate.getLblFieldText().setText("Date:");
        inputDate.getLblError().setText("");
        inputGender.getLblFieldText().setText("Gender:");
        inputGender.getLblError().setText("");
        inputGender.getRadioButton1().setText("MALE");
        inputGender.getRadioButton2().setText("FEMALE");
        

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSubmit;
    private components.fields.PanelInputDatePicker inputDate;
    private components.fields.PanelInputTextField inputFirstName;
    private components.fields.PanelInputRadio inputGender;
    private components.fields.PanelInputTextField inputLastName;
    private javax.swing.JMenuBar jMenuBar;
    private javax.swing.JMenu jMenuConfiguration;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItemForm1;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItemForm2;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItemForm3;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItemForm4;
    // End of variables declaration//GEN-END:variables

    private void prepareMenu() {
         jRadioButtonMenuItemForm1.setSelected(false);
         jRadioButtonMenuItemForm2.setSelected(true);
         jRadioButtonMenuItemForm3.setSelected(false);
         jRadioButtonMenuItemForm4.setSelected(false);
    }
}
